polls2/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls2/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	path('',views.IndexView.as_view(),name='index'),
	path('<int:pk>/', views.DetailView.as_view(),name='detail'),
	path('<int:pk>/results', views.ResultsView.as_view(),name='results'),
	path('<int:question_id>/vote', views.vote, name='vote'),
]

polls2/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=300)
	pub_date = models.DateTimeField('Date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		now = timezone.now()
		return now >= self.pub_date >= now - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=300)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

polls2/polls/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Question, Choice
from django.utils import timezone

# Create your views here.
class IndexView(generic.ListView):
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, question_id)
	try:
		selected_choice = request.POST['choice']
	except(KeyError, Choice.DoesNotExist):
		context = { 'question':question_id, 'error_message':'No Choice Selected' }
		return render(request, 'polls/detail.html', context)
	else:
		selected_choice = F('votes')+1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls/detail'), args=(question_id,))

polls2/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form method='post' action="{% url 'polls:vote' question.id %}">
{% csrf_token %}
{% for c in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ c.id }}">
		<label id="choice{{ forloop.counter }}">{{ c.choice_text }}</label>
{% endfor %}
<input type="submit" name="Vote">
</form>

polls2/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/styles.css' %}">
{% if latest_question_list %}
	<ul>
	{% for q in latest_question_list %}
		<li><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No poll questions yet</p>
{% endif %}

polls2/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for c in question.choice_set.all %}
	<li>{{ c.choice_text }} -- {{ c.votes }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again</a>